module.exports = {
	TWITER_CONSUMER_KEY:'qj0f8WjCxdPj1qd0nG7VWS3sf',
	TWITTER_CONSUMER_SECRET:'oScuNePMHUdwxokie5JXnv4GgSJyhBjMLvQFisppp1NUafrYTi',
	TWITTER_ACCESS_TOKEN:'BXCIo5xpRl1CAA52g3yssAAzRlWbx9t7Oqi3aRPz',
	TWITTER_ACCESS_TOKEN_SECRET:'S7aScfhqSZndN9sMIVPuJ6CQypBk1nww1Ws4gMW1g9r0S'
}