# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160925_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mail_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('PT', 'Patient'), ('NR', 'Nurse'), ('AD', 'Admin')], default='PT', max_length=2),
        ),
    ]
